export enum LanguageType {
  Zh = 'zh',
  En = 'en',
}
export type ComponentType =
  | 'Input'
  | 'InputTooltip'
  | 'InputGroup'
  | 'InputPassword'
  | 'InputSearch'
  | 'InputTextArea'
  | 'InputNumber'
  | 'MaxMinInput'
  | 'InputCountDown'
  | 'Select'
  | 'ApiSelect'
  | 'SearchSelect'
  | 'SearchModal'
  | 'MapField'
  | 'SelectOptGroup'
  | 'TreeSelect'
  | 'Transfer'
  | 'RadioButtonGroup'
  | 'RadioGroup'
  | 'Checkbox'
  | 'CheckboxGroup'
  | 'AutoComplete'
  | 'Cascader'
  | 'DatePicker'
  | 'RangeTimePicker'
  | 'MonthPicker'
  | 'RangePicker'
  | 'WeekPicker'
  | 'TimePicker'
  | 'Switch'
  | 'StrengthMeter'
  | 'Upload'
  | 'IconPicker'
  | 'Editor'
  | 'SingleUpload'
  | 'Render';
